# Secure Activation function for machine learning 

In [2]:
import ctypes 
from gmpy2 import * 
from numpy.ctypeslib import ndpointer 
import matplotlib.pyplot as plt
import numpy as np 
from ctypes import * 
from keras.datasets import mnist
import time



In [3]:
# mission6.so contains the library function for inner product functional encryption
lib=ctypes.CDLL("./mission6.so")
pyfinal= lib.Final


In [4]:
# loading MNIST
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [5]:
# random w matrix and x vector
w=(np.random.rand(25,25)*10).astype('int32')
x=np.random.rand(25)*10
x=x.astype('int32')

In [6]:
pyfinal.argtypes=[ndpointer(ctypes.c_int, flags="C_CONTIGUOUS"), 
ndpointer(ctypes.c_int, flags="C_CONTIGUOUS"),
ctypes.c_size_t,
]
pyfinal.restype=ctypes.c_int

In [7]:
def SecureActivation(w,x): 
	result= np.array([]).astype('int32')
	for i in range(w.shape[0]):
		temp=pyfinal(w[i],x,x.size)
		result=np.append(result,temp)
	return result

In [8]:
w

array([[2, 7, 3, 3, 3, 8, 9, 0, 8, 0, 8, 8, 7, 6, 7, 1, 7, 7, 2, 4, 1, 9,
        5, 9, 9],
       [1, 3, 5, 6, 5, 2, 5, 6, 9, 2, 4, 8, 1, 2, 5, 7, 6, 1, 4, 5, 0, 8,
        9, 4, 8],
       [1, 9, 2, 5, 4, 5, 1, 9, 7, 6, 5, 4, 8, 9, 1, 1, 7, 3, 1, 5, 8, 3,
        9, 4, 4],
       [5, 7, 8, 5, 9, 9, 5, 5, 5, 4, 9, 3, 2, 2, 9, 6, 7, 8, 6, 0, 4, 3,
        8, 6, 4],
       [1, 2, 9, 6, 6, 4, 1, 8, 1, 6, 3, 4, 9, 8, 4, 1, 8, 1, 6, 6, 4, 4,
        4, 5, 0],
       [6, 2, 4, 0, 9, 0, 9, 5, 0, 9, 3, 7, 5, 3, 0, 3, 1, 2, 0, 8, 8, 3,
        5, 4, 2],
       [2, 7, 5, 1, 8, 0, 7, 3, 2, 6, 8, 6, 5, 1, 1, 4, 5, 8, 6, 1, 3, 0,
        3, 7, 6],
       [4, 0, 6, 3, 3, 4, 2, 1, 8, 1, 3, 2, 1, 9, 6, 6, 8, 9, 3, 5, 7, 3,
        4, 9, 6],
       [3, 3, 8, 8, 5, 9, 5, 8, 9, 3, 0, 7, 1, 8, 9, 3, 4, 0, 0, 4, 4, 3,
        9, 9, 0],
       [6, 7, 6, 3, 1, 8, 3, 4, 2, 7, 4, 1, 2, 7, 4, 8, 1, 4, 3, 7, 6, 5,
        0, 3, 3],
       [1, 5, 6, 6, 4, 2, 8, 9, 3, 7, 1, 5, 1, 5, 6, 8, 6, 9, 7, 4, 0, 2,
      

In [9]:
x

array([9, 9, 4, 9, 4, 9, 6, 5, 2, 5, 5, 9, 7, 2, 0, 0, 9, 9, 9, 0, 8, 4,
       3, 9, 7], dtype=int32)

#### Checking the performance of inner product function using functional encryption

In [10]:
t=time.time()
SecureActivation(w,x)
nt=time.time()
print(nt - t)

0.04581809043884277


#### Checking the performance of dot function in numpy

In [11]:
t=time.time()
np.dot(w,x)
nt=time.time()
print(nt-t)


0.00014781951904296875


In [12]:
x_train=x_train[:500,:,:]

In [13]:
x_train = x_train/255

In [14]:
#forward
weights=np.random.rand(128,784)
weights1=(weights*10).astype('int32')

In [15]:
weights.shape

(128, 784)

In [16]:
tmp=x_train[0].flatten()
tmp1=(tmp*10).astype('int32')

In [17]:
res=SecureActivation(weights1,tmp1)

In [18]:
res=res/100

In [19]:
res

array([45.63, 37.4 , 44.47, 45.35, 47.18, 40.49, 45.5 , 43.42, 43.66,
       48.01, 46.3 , 48.57, 43.62, 44.55, 44.56, 44.86, 46.1 , 41.71,
       46.47, 42.12, 40.17, 41.23, 42.41, 46.98, 47.78, 50.26, 42.4 ,
       43.9 , 46.7 , 43.08, 48.27, 41.28, 44.19, 46.9 , 46.06, 42.63,
       44.5 , 44.64, 47.35, 41.79, 41.01, 44.24, 39.22, 42.91, 47.66,
       38.96, 45.17, 42.01, 45.85, 39.66, 46.96, 48.17, 46.99, 45.04,
       40.99, 45.45, 42.82, 46.14, 44.34, 45.89, 43.77, 45.61, 39.06,
       38.71, 40.36, 44.81, 40.18, 41.81, 43.84, 47.31, 43.55, 46.32,
       39.93, 43.42, 46.79, 44.98, 40.62, 43.77, 45.63, 39.8 , 42.92,
       47.54, 44.86, 45.05, 37.91, 45.14, 43.91, 44.92, 37.95, 43.7 ,
       48.51, 47.02, 48.35, 40.69, 42.23, 41.66, 48.97, 43.  , 43.03,
       44.53, 45.12, 46.83, 40.1 , 44.66, 40.7 , 43.24, 46.75, 42.34,
       45.12, 39.16, 43.17, 44.95, 49.1 , 46.48, 44.05, 44.73, 40.68,
       43.89, 41.85, 48.11, 45.51, 45.01, 44.84, 41.58, 40.21, 45.04,
       42.39, 40.34]

In [20]:
np.dot(weights,tmp)

array([55.88256032, 46.7351976 , 54.61853463, 55.77123794, 56.62209342,
       50.4229887 , 55.79980187, 53.68605836, 53.56236768, 58.57439247,
       56.27598787, 59.25273149, 53.47462218, 54.47914138, 55.00825316,
       54.97424633, 56.44364581, 51.47313055, 56.82395541, 52.32672901,
       49.93663361, 51.44075871, 52.25127607, 57.36389528, 58.41251086,
       61.26007826, 52.41360871, 54.24151763, 56.69239725, 52.79722998,
       58.73684237, 51.22718132, 54.82879177, 57.33481154, 56.06939264,
       52.41101742, 54.73560779, 54.46834327, 57.4510212 , 51.57728912,
       50.7068476 , 54.91686225, 49.16644944, 52.80383127, 58.02384136,
       48.78520117, 55.1317421 , 51.86133503, 56.38352794, 48.84575776,
       57.36308586, 58.63659128, 57.04796137, 55.03123986, 50.81814554,
       55.30292881, 52.84148896, 56.31612571, 54.24804252, 56.33496818,
       53.93509312, 56.24609106, 48.80456871, 48.17811915, 50.17124758,
       55.23491147, 49.94532994, 51.314269  , 54.1472367 , 57.46